# This file was generated by GoReleaser. DO NOT EDIT.
class Grump < Formula
  desc ""
  homepage "https://github.com/dhulihan/grump"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dhulihan/grump/releases/download/0.0.4/grump_0.0.4_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "16b9de9c7c71942378d92a5649856ee8bffd82a440804d057f695d7ae11d7d2d"
  elsif OS.linux?
  end

  def install
    bin.install "grump"
  end
end
